# Generated by Django 6.1 on 2026-08-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hospital_images/'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='star',
            field=models.FloatField(default=0.0),
        ),
    ]
