# Generated by Django 6.1 on 2026-08-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_hospital_image_hospital_star'),
    ]

    operations = [
        migrations.CreateModel(
            name='speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('schemes', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='schemes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
