# Generated by Django 6.1 on 2026-08-21 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_speciality_hospital_schemes'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='star',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
    ]
