# Generated by Django 6.1 on 2026-08-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_speciality_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='star',
            field=models.FloatField(default=0.0),
        ),
    ]
