# Generated by Django 6.1 on 2026-08-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_speciality_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='servise',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
