# Generated by Django 6.1 on 2026-08-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_hospital_servise'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='about',
            field=models.TextField(default='This hospital provides quality healthcare services with experienced doctors, modern medical facilities and patient-focused care.'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.TextField(default='Nagpur'),
        ),
    ]
