# Generated by Django 6.1 on 2026-08-27 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_hospital_about_alter_hospital_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt_name', models.CharField(max_length=200)),
                ('strength', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('salt_name', 'strength')},
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Group_name', models.TextField(blank=True)),
                ('is_generic', models.BooleanField(default=False)),
                ('composition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='hospital.composition')),
            ],
        ),
    ]
