# Generated by Django 6.1 on 2026-08-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_composition_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='tablets',
            field=models.FloatField(default=0.0),
        ),
    ]
